#ifndef GENUS2_HEC_VERSION_H
#define GENUS2_HEC_VERSION_H

#define GENUS2_HEC_VERSION "0.1.0"

#define GENUS2_HEC_MAJOR_VERSION (0)
#define GENUS2_HEC_MINOR_VERSION (1)
#define GENUS2_HEC_REVISION      (0)

#endif
