language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux

install:
- sudo apt-get update
- sudo apt-get install -y texinfo
- ./scripts/install-ntl-5.5.sh

script: ./scripts/build.sh

branches:
  only:
  - master
  - /.*/
