name: "Build"
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-libg2hec-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        compiler_c: [gcc, clang]
        compiler_cxx: [g++, clang++]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texinfo
          sudo apt-get install -y autotools-dev autoconf build-essential
      - name: Build
        env:
          CC: ${{ matrix.compiler_c }}
          CXX: ${{ matrix.compiler_cxx }}
        run: |
          cd ${{ github.workspace }}
          autoreconf -vi
          ./scripts/build.sh 
