name: "Documentation"
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publish-documentation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
    steps:
      - name: Checkout
        # v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y texinfo
          sudo apt install -y autotools-dev autoconf build-essential
      - name: Publish docs
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}
          autoreconf -vi
          ./scripts/publish-docs.sh 
