name: "Documentation"
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publish-documentation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y texinfo
          sudo apt install -y autotools-dev autoconf build-essential
      - name: Publish docs
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}
          autoreconf -vi
          ./scripts/publish-docs.sh 
