name: Sanity Checks
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-libg2hec-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        compiler_c: [gcc, clang]
        compiler_cxx: [g++, clang++]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y texinfo
          sudo apt install -y texlive-latex-extra
          sudo apt install -y autotools-dev autoconf build-essential bear
      - name: Build
        env:
          CC: ${{ matrix.compiler_c }}
          CXX: ${{ matrix.compiler_cxx }}
        run: |
          cd ${{ github.workspace }}
          autoreconf -vi
          ./scripts/build.sh distcheck

  shellcheck:
    name: 'shellcheck'
    strategy:
      fail-fast: false
      # Run on Linux and macos
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Install shellcheck on Ubuntu
        run: |
          sudo apt update
          sudo apt install shellcheck -y

      - if: ${{ matrix.os == 'macos-latest' }}
        name: Install shellcheck on macos
        run: |
          brew install shellcheck

      - name: Run shellcheck
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}/
          shellcheck --version
          for f in $(find scripts/ -type f); do
            if file "$f" | grep "shell script" &>/dev/null; then
              shellcheck "$f"
            fi
          done
